import type { StylePreset } from "../types";

export const STYLES: Record<string, StylePreset> = {
  neon: {
    bgColor: "#000000",
    bgGradient: ["#000000", "#0a0a2e"],
    activeColor: "#00ffff",
    inactiveColor: "#336666",
    highlightColor: "#ff00ff",
    fontSize: 72,
    fontFamily: "Arial, sans-serif",
    fontWeight: 700,
    glow: true,
    glowColor: "#00ffff",
    glowRadius: 20,
    wordAnimation: "pop",
    lineAnimation: "fade",
    particles: true,
  },
  minimal: {
    bgColor: "#ffffff",
    activeColor: "#111111",
    inactiveColor: "#aaaaaa",
    highlightColor: "#111111",
    fontSize: 64,
    fontFamily: "Georgia, serif",
    fontWeight: 400,
    glow: false,
    wordAnimation: "fade",
    lineAnimation: "slide-up",
    particles: false,
  },
  retro: {
    bgColor: "#1a0a00",
    bgGradient: ["#1a0a00", "#2a1500"],
    activeColor: "#ffcc00",
    inactiveColor: "#664400",
    highlightColor: "#ff6600",
    fontSize: 72,
    fontFamily: "Impact, sans-serif",
    fontWeight: 700,
    glow: true,
    glowColor: "#ffcc00",
    glowRadius: 15,
    wordAnimation: "slam",
    lineAnimation: "zoom",
    particles: true,
  },
  dreamy: {
    bgColor: "#0a0018",
    bgGradient: ["#0a0018", "#1a0030"],
    activeColor: "#cc99ff",
    inactiveColor: "#553377",
    highlightColor: "#ff99cc",
    fontSize: 68,
    fontFamily: "Georgia, serif",
    fontWeight: 400,
    glow: true,
    glowColor: "#cc99ff",
    glowRadius: 25,
    wordAnimation: "slide-up",
    lineAnimation: "fade",
    particles: true,
  },
  bold: {
    bgColor: "#000000",
    activeColor: "#ffffff",
    inactiveColor: "#555555",
    highlightColor: "#ffff00",
    fontSize: 80,
    fontFamily: "Arial Black, sans-serif",
    fontWeight: 900,
    glow: false,
    wordAnimation: "slam",
    lineAnimation: "slide-up",
    particles: false,
  },
};
